import Link from "next/link";
import { aggregateEngineeringEvaluation } from "@/lib/engineering-evaluation";
import { listEngineeringTasks } from "@/lib/engineering-task-store";
import { readSoftwareBenchmarkReport } from "@/lib/software-agent-benchmark";
import { headers } from "next/headers";
import { notFound } from "next/navigation";
import { resolveOrganizationContext } from "@/lib/approval-policy";

export const dynamic = "force-dynamic";

const verdictLabels = { accepted: "接受", needs_changes: "需要改进", rejected: "不可用" } as const;
const verdictTones = { accepted: "bg-emerald-50 text-emerald-700", needs_changes: "bg-amber-50 text-amber-700", rejected: "bg-red-50 text-red-700" } as const;

export default async function EvaluationsPage() {
  const organization = resolveOrganizationContext(await headers());
  if (!organization) notFound();
  const evaluation = aggregateEngineeringEvaluation(await listEngineeringTasks(organization.id));
  const benchmark = await readSoftwareBenchmarkReport();
  const { summary } = evaluation;
  const cards = [
    ["人工接受率", `${summary.acceptanceRate}%`, `${summary.accepted}/${summary.reviewed} 条已复核结果被接受`],
    ["平均证据评分", `${summary.averageScore}`, `每个报告平均深读 ${summary.averageEvidenceFiles} 个文件`],
    ["自动可靠率", `${summary.reliableRate}%`, "由证据覆盖规则给出的 reliable 比例"],
    ["平均 Runtime 耗时", `${summary.averageRuntimeMs}ms`, `${summary.toolCalls} 次工具调用，${summary.failedSpans} 个失败 Span`],
  ];
  return <main className="mx-auto max-w-7xl p-6 lg:p-9"><header><p className="text-sm font-medium text-indigo-600">EVALUATION CONTROL PLANE</p><h1 className="mt-1 text-3xl font-semibold">质量评估看板</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">把自动证据评分与人工复核分开统计。自动分数回答“证据是否充分”，人工结论回答“业务结果是否真正可用”。</p></header>
    <section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value, detail]) => <article key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-medium text-slate-500">{label}</p><p className="mt-3 text-3xl font-semibold text-slate-900">{value}</p><p className="mt-2 text-xs leading-5 text-slate-400">{detail}</p></article>)}</section>
    <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-medium text-indigo-600">OFFLINE BENCHMARK</p><h2 className="mt-1 font-semibold">版本化回归基准</h2><p className="mt-2 text-sm text-slate-500">固定 GitHub PR / Issue 快照与合成边界样本；执行 <code>npm run eval:software</code> 更新。</p></div>{benchmark ? <span className={`rounded-full px-3 py-1.5 text-xs font-medium ${benchmark.summary.passed === benchmark.summary.total ? "bg-emerald-50 text-emerald-700" : "bg-red-50 text-red-700"}`}>{benchmark.summary.passed}/{benchmark.summary.total} 通过</span> : <span className="rounded-full bg-slate-100 px-3 py-1.5 text-xs text-slate-500">尚未运行</span>}</div>{benchmark && <div className="mt-5 grid gap-4 sm:grid-cols-5"><div><p className="text-xs text-slate-400">基准版本</p><p className="mt-1 font-mono text-sm text-slate-700">{benchmark.version}</p></div><div><p className="text-xs text-slate-400">整体通过率</p><p className="mt-1 text-xl font-semibold">{benchmark.summary.passRate}%</p></div><div><p className="text-xs text-slate-400">真实样本</p><p className="mt-1 text-xl font-semibold">{benchmark.summary.realPassed}/{benchmark.summary.realTotal}</p></div><div><p className="text-xs text-slate-400">PR Precision</p><p className="mt-1 text-xl font-semibold">{benchmark.summary.prPrecision}%</p></div><div><p className="text-xs text-slate-400">PR Recall</p><p className="mt-1 text-xl font-semibold">{benchmark.summary.prRecall}%</p></div></div>}{benchmark && benchmark.results.some((result) => !result.passed) && <div className="mt-5 rounded-xl bg-red-50 p-4 text-xs text-red-700">失败用例：{benchmark.results.filter((result) => !result.passed).map((result) => result.id).join("、")}</div>}</section>
    {benchmark && <section className="mt-6 grid gap-4 lg:grid-cols-3">{([['按仓库', benchmark.breakdown.repositories], ['按语言', benchmark.breakdown.languages], ['按风险类型', benchmark.breakdown.riskTypes]] as const).map(([title, groups]) => <article key={title} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-medium text-indigo-600">REAL SAMPLE BREAKDOWN</p><h2 className="mt-1 font-semibold">{title}</h2><div className="mt-4 space-y-3">{groups.map((group) => <div key={group.key} className="flex items-center gap-3 text-xs"><span className="min-w-0 flex-1 truncate text-slate-600">{group.key}</span><div className="h-1.5 w-20 overflow-hidden rounded-full bg-slate-100"><div className={group.passRate === 100 ? "h-full bg-emerald-500" : "h-full bg-amber-500"} style={{ width: `${group.passRate}%` }} /></div><span className="w-14 text-right font-medium text-slate-700">{group.passed}/{group.total}</span></div>)}</div></article>)}</section>}
    <section className="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><header className="border-b border-slate-100 px-6 py-5"><p className="text-xs font-medium text-indigo-600">QUALITY BY AGENT</p><h2 className="mt-1 font-semibold">业务 Agent 对比</h2></header><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-6 py-3 font-medium">Agent</th><th className="px-4 py-3 font-medium">任务数</th><th className="px-4 py-3 font-medium">已完成</th><th className="px-4 py-3 font-medium">人工复核</th><th className="px-4 py-3 font-medium">接受率</th><th className="px-4 py-3 font-medium">平均评分</th></tr></thead><tbody className="divide-y divide-slate-100">{evaluation.byUseCase.map((row) => <tr key={row.useCase}><td className="px-6 py-4 font-medium text-slate-800">{row.label}</td><td className="px-4 py-4 text-slate-500">{row.total}</td><td className="px-4 py-4 text-slate-500">{row.completed}</td><td className="px-4 py-4 text-slate-500">{row.reviewed}</td><td className="px-4 py-4"><div className="flex items-center gap-3"><div className="h-1.5 w-24 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-emerald-500" style={{ width: `${row.acceptanceRate}%` }} /></div><span className="text-xs text-slate-600">{row.acceptanceRate}%</span></div></td><td className="px-4 py-4 text-slate-600">{row.averageScore || "—"}</td></tr>)}</tbody></table></div></section>
    <div className="mt-6 grid gap-6 lg:grid-cols-[1fr_320px]"><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><header className="border-b border-slate-100 px-6 py-5"><p className="text-xs font-medium text-indigo-600">HUMAN REVIEW</p><h2 className="mt-1 font-semibold">最近人工复核</h2></header>{evaluation.recentReviews.length ? <div className="divide-y divide-slate-100">{evaluation.recentReviews.map((task) => <Link key={task.id} href={`/engineering/tasks/${task.id}`} className="flex items-center gap-4 px-6 py-4 hover:bg-slate-50"><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-slate-800">{task.input.question}</p><p className="mt-1 truncate text-xs text-slate-400">{task.input.repository.owner}/{task.input.repository.name}{task.humanReview?.note ? ` · ${task.humanReview.note}` : ""}</p></div>{task.humanReview && <span className={`rounded-full px-2.5 py-1 text-xs ${verdictTones[task.humanReview.verdict]}`}>{verdictLabels[task.humanReview.verdict]}</span>}</Link>)}</div> : <p className="p-6 text-sm text-slate-500">还没有人工复核。打开一个已完成任务，选择“接受 / 需要改进 / 不可用”。</p>}</section><aside className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-medium text-indigo-600">RUNTIME SIGNALS</p><dl className="mt-4 space-y-4 text-sm"><div className="flex justify-between"><dt className="text-slate-500">自动重试率</dt><dd className="font-medium">{summary.retryRate}%</dd></div><div className="flex justify-between"><dt className="text-slate-500">最终失败</dt><dd className="font-medium text-red-600">{summary.failed}</dd></div><div className="flex justify-between"><dt className="text-slate-500">人工取消</dt><dd className="font-medium">{summary.cancelled}</dd></div><div className="flex justify-between"><dt className="text-slate-500">需要改进</dt><dd className="font-medium text-amber-600">{summary.needsChanges}</dd></div><div className="flex justify-between"><dt className="text-slate-500">不可用</dt><dd className="font-medium text-red-600">{summary.rejected}</dd></div></dl><p className="mt-5 border-t border-slate-100 pt-4 text-xs leading-5 text-slate-400">接受率仅基于已人工复核任务计算，避免把“无人评价”误当作接受。</p></aside></div>
  </main>;
}
